/**
 * @file lib/threeMF/ThreeMFParser.ts
 * Master 3MF Parser & Slicer Detection Engine.
 *
 * Responsibilities:
 * - Safe ZIP extraction with zip-bomb prevention.
 * - Extracts 3D geometry objects from `3D/3dmodel.model`.
 * - Adapter routing: Bambu Studio, OrcaSlicer, Creality Print, PrusaSlicer.
 * - Multi-plate data aggregation.
 * - Strict verification: NEVER returns fake or estimated metrics.
 */

import JSZip from 'jszip';
import {
  ThreeMFProject,
  ThreeMFState,
  PlateInfo,
  ObjectInfo,
  ThreeMFMetadata,
} from '../../types/threeMF';
import { BaseSlicerParser } from './parsers/BaseSlicerParser';
import { BambuStudioParser } from './parsers/BambuStudioParser';
import { OrcaSlicerParser } from './parsers/OrcaSlicerParser';
import { CrealityPrintParser } from './parsers/CrealityPrintParser';
import { PrusaSlicerParser } from './parsers/PrusaSlicerParser';

// Security limits
const MAX_FILE_SIZE_BYTES = 150 * 1024 * 1024; // 150 MB
const MAX_ENTRIES_COUNT = 5000;
const MAX_UNCOMPRESSED_SIZE_BYTES = 350 * 1024 * 1024; // 350 MB

export class ThreeMFParser {
  private parsers: BaseSlicerParser[];

  constructor() {
    // Order matters: check Orca before Bambu because Orca shares metadata files
    this.parsers = [
      new OrcaSlicerParser(),
      new BambuStudioParser(),
      new CrealityPrintParser(),
      new PrusaSlicerParser(),
    ];
  }

  /**
   * Main entry point to parse a .3mf file from ArrayBuffer / Blob.
   */
  async parseFile(
    fileBuffer: ArrayBuffer,
    fileName: string = 'model.3mf'
  ): Promise<ThreeMFProject> {
    const fileSize = fileBuffer.byteLength;

    // 1. File size security check
    if (fileSize > MAX_FILE_SIZE_BYTES) {
      return this.createErrorProject(
        fileName,
        fileSize,
        'INVALID',
        `Kích thước file (${Math.round(fileSize / (1024 * 1024))}MB) vượt quá giới hạn an toàn 150MB.`
      );
    }

    // 2. Open ZIP container
    let zip: JSZip;
    try {
      zip = await JSZip.loadAsync(fileBuffer);
    } catch {
      return this.createErrorProject(
        fileName,
        fileSize,
        'INVALID',
        'File không phải là file nén ZIP / 3MF hợp lệ hoặc đã bị lỗi định dạng.'
      );
    }

    // 3. Zip bomb & entry inspection
    const fileEntries = Object.keys(zip.files);
    if (fileEntries.length > MAX_ENTRIES_COUNT) {
      return this.createErrorProject(
        fileName,
        fileSize,
        'INVALID',
        `File chứa quá nhiều tệp con (${fileEntries.length}), có dấu hiệu bất thường.`
      );
    }

    // 4. Verify 3MF core structure (Open Packaging Conventions)
    const has3DModel = fileEntries.some((f) => /3d\/3dmodel\.model$/i.test(f));
    if (!has3DModel) {
      return this.createErrorProject(
        fileName,
        fileSize,
        'UNSUPPORTED',
        'Không tìm thấy file cốt lõi 3D/3dmodel.model. Đây có thể không phải là tệp 3MF hợp lệ.'
      );
    }

    // 5. Parse 3D objects from 3D/3dmodel.model
    const modelObjects = await this.extractModelObjects(zip, fileEntries);

    // 6. Match slicer adapter
    let matchedParser: BaseSlicerParser | null = null;
    for (const parser of this.parsers) {
      try {
        if (await parser.matches(fileEntries, zip)) {
          matchedParser = parser;
          break;
        }
      } catch {
        // continue to next parser
      }
    }

    let parsedMetadata: Partial<ThreeMFMetadata> = {
      detectedFiles: [],
      hasGcode: false,
    };
    let plates: PlateInfo[] = [];
    let isSliced = false;
    const warnings: string[] = [];

    if (matchedParser) {
      try {
        const result = await matchedParser.parse(zip, fileEntries, modelObjects);
        parsedMetadata = { ...parsedMetadata, ...result.metadata };
        plates = result.plates;
        isSliced = result.isSliced;
        warnings.push(...result.warnings);
      } catch (err: unknown) {
        warnings.push(`Cảnh báo phân tích adapter: ${err instanceof Error ? err.message : String(err)}`);
      }
    } else {
      // No specific slicer detected. Check if any generic slicer configs or G-code exist.
      const hasConfig = fileEntries.some((f) => /metadata\/.*\.(?:config|json|ini)$/i.test(f));
      const hasGcode = fileEntries.some((f) => /\.gcode$/i.test(f));

      if (hasConfig || hasGcode) {
        parsedMetadata.slicer = 'Slicer không xác định';
        warnings.push('Phát hiện cấu hình in nhưng chưa nhận diện được cấu trúc slicer tương thích hoàn toàn.');
      }
    }

    // If no plates were generated by parser, create default plate from 3D model objects
    if (plates.length === 0) {
      const objList = Array.from(modelObjects.values());
      plates.push({
        id: 'plate_1',
        plateIndex: 1,
        name: 'Bàn in 1',
        objects: objList,
        objectCount: objList.length > 0 ? objList.length : 1,
        filament: [],
        totalFilamentWeightGrams: 0,
        printTimeSeconds: 0,
        slicer: parsedMetadata.slicer,
        printer: parsedMetadata.printer,
        source: 'UNAVAILABLE',
        warnings: [],
      });
    }

    // 7. Calculate Multi-Plate Aggregations
    const totalFilamentWeightGrams = Math.round(
      plates.reduce((sum, plate) => sum + plate.totalFilamentWeightGrams, 0) * 100
    ) / 100;

    const totalPrintTimeSeconds = plates.reduce(
      (sum, plate) => sum + plate.printTimeSeconds,
      0
    );

    const totalObjectCount = plates.reduce(
      (sum, plate) => sum + plate.objectCount,
      0
    );

    // 8. Determine ThreeMFState
    let state: ThreeMFState = 'MODEL_ONLY';
    if (isSliced && (totalFilamentWeightGrams > 0 || totalPrintTimeSeconds > 0)) {
      state = 'SLICED';
    } else if (
      parsedMetadata.slicer ||
      parsedMetadata.printer ||
      parsedMetadata.layerHeightMm !== undefined ||
      fileEntries.some((f) => /metadata\/.*(config|ini|json)/i.test(f))
    ) {
      state = 'CONFIGURED';
      warnings.push(
        'Không thể xác định chính xác lượng filament và thời gian in từ file này. File chứa cấu hình dự án nhưng chưa được cắt lớp (slice).'
      );
    } else {
      state = 'MODEL_ONLY';
      warnings.push(
        'File 3MF dạng hình học thuần túy (Model-Only). Chưa có thông tin cấu hình slicer, bàn in hay kết quả cắt lớp.'
      );
    }

    const finalMetadata: ThreeMFMetadata = {
      slicer: parsedMetadata.slicer || (state === 'MODEL_ONLY' ? 'Chưa xác định' : 'Chuẩn 3MF'),
      slicerVersion: parsedMetadata.slicerVersion,
      printer: parsedMetadata.printer || 'Mặc định',
      printProfileName: parsedMetadata.printProfileName,
      nozzleDiameter: parsedMetadata.nozzleDiameter || 0.4,
      layerHeightMm: parsedMetadata.layerHeightMm,
      infillPercent: parsedMetadata.infillPercent,
      filamentProfiles: parsedMetadata.filamentProfiles || [],
      hasGcode: parsedMetadata.hasGcode || false,
      detectedFiles: fileEntries.filter((f) => /metadata|gcode/i.test(f)),
    };

    return {
      state,
      fileName,
      fileSize,
      metadata: finalMetadata,
      plates,
      totalFilamentWeightGrams,
      totalPrintTimeSeconds,
      totalObjectCount: totalObjectCount > 0 ? totalObjectCount : 1,
      warnings,
      canSliceInBrowser: false,
      rawSlicerDetected: parsedMetadata.slicer,
    };
  }

  /**
   * Reads 3D/3dmodel.model and extracts all object definitions.
   */
  private async extractModelObjects(
    zip: JSZip,
    fileEntries: string[]
  ): Promise<Map<string, ObjectInfo>> {
    const objectMap = new Map<string, ObjectInfo>();
    const modelPath = fileEntries.find((f) => /3d\/3dmodel\.model$/i.test(f));
    if (!modelPath) return objectMap;

    const file = zip.file(modelPath);
    if (!file) return objectMap;

    try {
      const xmlText = await file.async('string');
      
      // Simple regex parser for <object id="..." name="...">
      const objectRegex = /<object\b([^>]*?)>/gi;
      let match: RegExpExecArray | null;

      while ((match = objectRegex.exec(xmlText)) !== null) {
        const attrs = match[1];
        const idMatch = attrs.match(/\bid\s*=\s*["']([^"']+)["']/i);
        const nameMatch = attrs.match(/\bname\s*=\s*["']([^"']+)["']/i);
        const typeMatch = attrs.match(/\btype\s*=\s*["']([^"']+)["']/i);

        // Ignore support meshes if marked
        if (typeMatch && typeMatch[1].toLowerCase() === 'support') continue;

        if (idMatch) {
          const id = idMatch[1];
          const name = nameMatch ? nameMatch[1] : `Chi tiết ${id}`;
          objectMap.set(id, { id, name });
        }
      }

      // Also check <build><item objectid="..."/></build> to count actual instances placed on bed
      const buildItemsRegex = /<item\b([^>]*?)\/?>/gi;
      let buildCount = 0;
      while ((buildItemsRegex.exec(xmlText)) !== null) {
        buildCount++;
      }

      // If build items exist and exceed object definitions (cloned parts), note that
      if (buildCount > objectMap.size && objectMap.size > 0) {
        // Expand copies
        const originalObjects = Array.from(objectMap.values());
        for (let i = objectMap.size + 1; i <= buildCount; i++) {
          const base = originalObjects[(i - 1) % originalObjects.length];
          objectMap.set(`copy_${i}`, {
            id: `copy_${i}`,
            name: `${base.name} (Bản sao ${i})`,
          });
        }
      }
    } catch {
      // fallback gracefully
    }

    return objectMap;
  }

  private createErrorProject(
    fileName: string,
    fileSize: number,
    state: ThreeMFState,
    errorMessage: string
  ): ThreeMFProject {
    return {
      state,
      fileName,
      fileSize,
      metadata: {
        slicer: 'Không xác định',
        printer: 'Không xác định',
        hasGcode: false,
        detectedFiles: [],
      },
      plates: [],
      totalFilamentWeightGrams: 0,
      totalPrintTimeSeconds: 0,
      totalObjectCount: 0,
      warnings: [errorMessage],
      errorMessage,
      canSliceInBrowser: false,
    };
  }
}
